name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@v1
        with:
          license: ${{ secrets.RETYPE_SECRET }}
        env:
          version: 12.5.8

      - uses: retypeapp/action-github-pages@v1
        with:
          update-branch: true
